name: Build README

permissions:
  contents: write
  
on:
  push:
    branches:
    - master
    paths-ignore:
    - README.md
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        # necessary for github-action-til-autoformat-readme
        fetch-depth: 0
    - name: Autoformat README
      uses: cflynn07/github-action-til-autoformat-readme@1.1.0
      with:
        description: |
          📚 개발 관련 학습 내용을 기록하는 저장소입니다.
          매일 새롭게 배운 내용과 개발 관련 팁을 정리합니다.
        footer: |
          [1]: https://github.com/seongjun-noh/TIL
          [2]: https://seongjun-noh.github.io/
        list_most_recent: 5 # optional, lists most recent TILS below description
        date_format: "2006-01-02" # optional, must align to https://golang.org/pkg/time/#Time.Format
